add_newline = true

[aws]
disabled = true

[battery]
disabled = true

[cmd_duration]
disabled = false
min_time = 2

[dotnet]
disabled = true

[golang]
disabled = true

[kubernetes]
disabled = true

[nix_shell]
disabled = true

[nodejs]
disabled = false

[package]
disabled = true

[python]
disabled = true

[ruby]
disabled = false
