set-option -g default-terminal "tmux-256color"
set-option -sa terminal-overrides ',alacritty:RGB'

set-option -g default-command "/usr/local/bin/fish"

set-option -g status-interval 5
set-window-option -g automatic-rename on
set-option -g set-titles on

set-option -g mouse on
set-option -g history-limit 10000
set-option -g set-clipboard external
set-window-option -g mode-keys vi
set-window-option -g xterm-keys on
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "reattach-to-user-namespace pbcopy"
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "reattach-to-user-namespace pbcopy"

set-window-option -g monitor-activity on
set-option -g visual-activity off
set-option -g activity-action none

set-option -g base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on
set-window-option -g aggressive-resize on
set-option -sg escape-time 10

bind | split-window -h
bind - split-window -v
bind-key r source-file ~/.tmux.conf \; display '~/.tmux.conf sourced'
bind-key X kill-pane
bind-key / copy-mode \; send-key ?
bind-key P 'capture-pane' \; capture-pane -S - \; save-buffer /tmp/tmux \; delete-buffer
unbind '"'
unbind %

## COLORSCHEME: gruvbox dark
set-option -g status "on"

# default statusbar color
set-option -g status-style bg=colour237,fg=colour223 # bg=bg1, fg=fg1

# default window title colors
set-window-option -g window-status-style bg=colour214,fg=colour237 # bg=yellow, fg=bg1

# default window with an activity alert
set-window-option -g window-status-activity-style bg=colour237,fg=colour248 # bg=bg1, fg=fg3

# active window title colors
set-window-option -g window-status-current-style bg=red,fg=colour237 # fg=bg1

# pane border
set-option -g pane-active-border-style fg=colour250 #fg2
set-option -g pane-border-style fg=colour237 #bg1

# message infos
set-option -g message-style bg=colour239,fg=colour223 # bg=bg2, fg=fg1

# writing commands inactive
set-option -g message-command-style bg=colour239,fg=colour223 # bg=fg3, fg=bg1

# pane number display
set-option -g display-panes-active-colour colour250 #fg2
set-option -g display-panes-colour colour237 #bg1

# clock
set-window-option -g clock-mode-colour colour109 #blue

# bell
set-window-option -g window-status-bell-style bg=colour167,fg=colour235 # bg=red, fg=bg

## Theme settings mixed with colors (unfortunately, but there is no cleaner way)
set-option -g status-justify "left"
set-option -g status-left-style none
set-option -g status-left-length "80"
set-option -g status-right-style none
set-option -g status-right-length "80"
set-window-option -g window-status-separator ""

set-option -g status-left "#[fg=colour248, bg=colour241] \uf2d0 #S #[fg=colour241, bg=colour237, nobold, noitalics, nounderscore]"
set-option -g status-right "#[fg=colour239, bg=colour237, nobold, nounderscore, noitalics]#[fg=colour246,bg=colour239] %Y-%m-%d  %H:%M #[fg=colour248, bg=colour239, nobold, noitalics, nounderscore]#[fg=colour237, bg=colour248]  #(cd #{pane_current_path}; git rev-parse --abbrev-ref HEAD || echo 'no git') "

set-window-option -g window-status-current-format "#[fg=colour237, bg=colour214, nobold, noitalics, nounderscore]#[fg=colour239, bg=colour214] #I#{?window_activity_flag,*,}#{?window_bell_flag,!,} #[fg=colour239, bg=colour214, bold] #W #[fg=colour214, bg=colour237, nobold, noitalics, nounderscore]"
set-window-option -g window-status-format "#[fg=colour237,bg=colour239,noitalics]#[fg=colour223,bg=colour239] #I#{?window_activity_flag,*,}#{?window_bell_flag,!,} #[fg=colour223, bg=colour239] #W #[fg=colour239, bg=colour237, noitalics]"
