#!/bin/sh

set -eu
set -f # disable globbing
export IFS=' '

echo "Uploading $OUT_PATHS ..."

if /run/current-system/sw/bin/attic push nifoc-systems "$OUT_PATHS"; then
  exit 0
else
  echo "Ignoring error ..."
  exit 0
fi

