#!/usr/bin/env fish

pushd ~/.config/nixpkgs
rm -rf result

set system_old (readlink /run/current-system)
env TERM=xterm-256color darwin-rebuild switch --flake .
set system_new (readlink /run/current-system)

nvd diff "$system_old" "$system_new"

rm -f result
popd
