version: 2
root-markers:
  - .git/
  - flake.nix
lint-debounce: '200ms'

tools:
  dockerfile-hadolint: &dockerfile-hadolint
    lint-command: 'efm-hadolint'
    lint-formats:
      - '%f:%l:%trror: %m'
      - '%f:%l:%tarning: %m'
      - '%f:%l:%tnfo: %m'
      - '%f:%l:%ttyle: %m'

  elixir-credo: &elixir-credo
    lint-command: >
      mix credo suggest --all-priorities --format flycheck --read-from-stdin ${INPUT} |
      sed "s/ R:/ H:/; s/ D:/ I:/; s/ C:/ W:/"
    lint-stdin: true
    lint-formats:
      - '%f:%l:%c: %t: %m'
      - '%f:%l: %t: %m'
    root-markers:
      - mix.lock
      - mix.exs

  eruby-erb: &eruby-erb
    lint-command: 'erb -x -T - | ruby -c'
    lint-stdin: true
    lint-offset: 1

  fish-indent: &fish-indent
    format-command: 'fish_indent'
    format-stdin: true

  javascript-eslint: &javascript-eslint
    lint-command: 'eslint_d -f visualstudio --stdin --stdin-filename ${INPUT}'
    lint-ignore-exit-code: true
    lint-stdin: true
    lint-formats:
      - "%f(%l,%c): %tarning %m"
      - "%f(%l,%c): %rror %m"
    format-command: 'eslint_d --fix-to-stdout --stdin --stdin-filename=${INPUT}'
    format-stdin: true
    root-markers:
      - .eslintrc.js

  sh-shfmt: &sh-shfmt
    format-command: 'shfmt -i 2'
    format-stdin: true

  sh-shellcheck: &sh-shellcheck
    lint-command: 'shellcheck -f gcc -x'
    lint-formats:
      - '%f:%l:%c: %trror: %m'
      - '%f:%l:%c: %tarning: %m'
      - '%f:%l:%c: %tote: %m'

languages:
  dockerfile:
    - <<: *dockerfile-hadolint

  elixir:
    - <<: *elixir-credo

  eruby:
    - <<: *eruby-erb

  fish:
    - <<: *fish-indent

  javascript:
    - <<: *javascript-eslint

  sh:
    - <<: *sh-shellcheck
    - <<: *sh-shfmt
