vim.cmd('augroup nifoc_cusorline')
  vim.cmd('autocmd!')
  vim.cmd('autocmd FileType TelescopePrompt setlocal nocursorline')
  vim.cmd('autocmd FileType NvimTree setlocal nocursorline')
vim.cmd('augroup end')
