when:
  - event: push
    branch: master
  - event: manual
matrix:
  arch:
    - amd64
    - arm64
labels:
  type: nix
  arch: ${arch}
steps:
  - name: build
    image: bash
    commands:
      - nix-fast-build --eval-workers 2
