when:
  - event: cron
    cron: update_flake
  - event: manual
labels:
  type: podman
clone:
  git:
    image: quay.io/woodpeckerci/plugin-git
    settings:
      recursive: true
      submodule_override:
        private: https://git.kempkens.io/daniel/dotfiles-private.git
steps:
  - name: update
    image: ghcr.io/lix-project/lix:latest
    commands:
      - echo 'experimental-features = nix-command flakes flake-self-attrs' >> /etc/nix/nix.conf
      - nix run '.#write-flake'
  - name: push
    image: docker.io/appleboy/drone-git-push
    settings:
      branch: master
      remote: ssh://forgejo@git.kempkens.io/daniel/dotfiles.git
      commit: true
      commit_message: "chore(deps): update flake"
      author_name: Actions Bot
      author_email: daniel+actions-bot@kempkens.io
      ssh_key:
        from_secret: push_ssh_key
