name: Build
on:
  push:
    branches: ['master']
    paths:
      - 'flake.lock'
      - 'home/programs/nvim/plugins.nix'
      - '.github/workflows/build.yml'
jobs:
  build-arm64-system:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
      - uses: samueldr/lix-gha-installer-action@v2025-01-24.prerelease
      - name: Build adsb-antenna
        run: nix build '.#nixosConfigurations.adsb-antenna.config.system.build.toplevel'
