name: Build
on:
  push:
    branches: ['master']
    paths:
      - 'flake.lock'
      - '.github/workflows/build.yml'
jobs:
  build-apple-system:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v5
      - uses: NixOS/nix-installer-action@main
      - uses: Mic92/niks3-action@v1
        with:
          server-url: https://niks3-cache.kempkens.network
      - name: Prepare Build
        run: rm -rf private .gitmodules .git/modules/private && sed -i .bak1 '/self.submodules = true;/d' flake.nix && sed -i .bak2 '/.\/private\/modules/d' flake.nix
      - name: Build Pallas
        run: nix build '.#darwinConfigurations.Pallas.config.system.build.toplevel'
