name: Build

on:
  push:
    branches: ['master']

jobs:
  build-x86_64-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixpkgs-unstable
    - uses: cachix/cachix-action@v12
      with:
        name: nifoc
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build '.#nixosConfigurations.attic.pkgs.attic-server'
    - run: nix build '.#nixosConfigurations.attic.pkgs.attic-client'
