name: Build

on:
  push:
    branches: ['master']
    paths:
      - 'flake.lock'

jobs:
  build-x86_64-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixpkgs-unstable
    - uses: cachix/cachix-action@v12
      with:
        name: nifoc
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build '.#nixosConfigurations.tanker.pkgs.attic-server'
    - run: nix build '.#nixosConfigurations.tanker.pkgs.attic-client'
    - run: nix build '.#nixosConfigurations.tanker.pkgs.deploy-rs'

  build-arm64-linux:
    runs-on: buildjet-2vcpu-ubuntu-2204-arm
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixpkgs-unstable
    - uses: cachix/cachix-action@v12
      with:
        name: nifoc
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build '.#nixosConfigurations.adsb-antenna.pkgs.attic-client'
    - run: nix build '.#nixosConfigurations.adsb-antenna.pkgs.deploy-rs'
