name: Build
on:
  push:
    branches: ['master']
    paths:
      - 'flake.lock'
      - '.github/workflows/build.yml'
jobs:
  build-apple-system:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v5
      - uses: NixOS/nix-installer-action@main
      - uses: Mic92/niks3-action@v1
        with:
          server-url: https://niks3-cache.kempkens.network
      - run: nix run 'nixpkgs#nix-fast-build' -- --skip-cached
