name: Build

on:
  push:
    branches: ['master']
    paths:
      - 'flake.lock'

jobs:
  build-x86_64-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@v4
    - name: Run the Magic Nix Cache
      uses: DeterminateSystems/magic-nix-cache-action@v1
    - uses: cachix/cachix-action@v12
      with:
        name: nifoc
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build '.#nixosConfigurations.tanker.pkgs.attic-server'
    - run: nix build '.#nixosConfigurations.tanker.pkgs.attic-client'
    - run: nix build '.#nixosConfigurations.tanker.pkgs.deploy-rs'

  build-arm64-linux:
    runs-on: buildjet-2vcpu-ubuntu-2204-arm
    steps:
    - uses: actions/checkout@v3
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@v4
    - uses: cachix/cachix-action@v12
      with:
        name: nifoc
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build '.#nixosConfigurations.adsb-antenna.pkgs.attic-client'
    - run: nix build '.#nixosConfigurations.adsb-antenna.pkgs.deploy-rs'
